name: YToo_Auto

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/YTooTelecom/Aoc.git ~/Aoc
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Aoc
          npm install
          npm install cron
          npm install request
      - name: '运行 【YToo_Auto】'
        run: |
          cd ~/Aoc   
          node YToo.A-2.js
        env:
          loadresourcebody: ${{ secrets.loadresourcebody }}
          loadresourcekey: ${{ secrets.loadresourcekey }}
          sploadresourcebody: ${{ secrets.sploadresourcebody }}
          sploadresourcekey: ${{ secrets.sploadresourcekey }}
          withdrawbody: ${{ secrets.withdrawbody }}
          bubblebody: ${{ secrets.bubblebody }}
          receivebody: ${{ secrets.receivebody }}
          signinactionbody: ${{ secrets.signinactionbody }}
          readlotterybody: ${{ secrets.readlotterybody }}
          videolotterybody: ${{ secrets.videolotterybody }}
          luckylotterybody: ${{ secrets.luckylotterybody }}
          luckyredurl: ${{ secrets.luckyredurl }}
          luckyredbody: ${{ secrets.luckyredbody }}
          sharebody: ${{ secrets.sharebody }}
          booktaskurl: ${{ secrets.booktaskurl }}
          booktaskbody: ${{ secrets.booktaskbody }}
          spsigninactionbody: ${{ secrets.spsigninactionbody }}
          spreadcoinurl: ${{ secrets.spreadcoinurl }}
          spreadcoinbody: ${{ secrets.spreadcoinbody }}
          sp1videocoinbody: ${{ secrets.sp1videocoinbody }}
          sp2videocoinbody: ${{ secrets.sp2videocoinbody }}
          spsharebody: ${{ secrets.spsharebody }}
          lotteryinfourl: ${{ secrets.lotteryinfourl }}
          videoinfourl: ${{ secrets.videoinfourl }}
          spvideoinfourl: ${{ secrets.spvideoinfourl }}
